cdk8s-team/cdk8s

packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js
packages/cdk8s-cli/templates/python-app/Pipfile
packages/cdk8s-cli/templates/python-app/main.py
packages/cdk8s-cli/templates/python-app/synth.sh

The command `cdk8s init python-app` will create a new python cdk8s project.
NOTE: this is intentionally not documented yet since we still don’t support `cdk8s gen` for python, so basically this only allows defining resources by directly instantiating `ApiObject`s. But this is still functional.

feat(cli): python project template

---

packages/cdk8s-cli/bin/cmds/import.ts
packages/cdk8s-cli/bin/cmds/init.ts
packages/cdk8s-cli/bin/cmds/synth.ts
packages/cdk8s-cli/lib/util.ts
packages/cdk8s-cli/templates/typescript-app/package.json
packages/cdk8s-cli/test/init.test.ts
packages/cdk8s-cli/test/util.ts
packages/cdk8s/lib/app.ts

A universal command to synthesize manifests for an app. It basically just executes the command specified in `--app` with the specified output directory and expects to find *.k8s.yaml files in there.
Resolves #41

feat(cli): cdk8s synth

---

packages/cdk8s-cli/lib/import.ts
packages/cdk8s-cli/lib/jsii.ts
packages/cdk8s-cli/lib/util.ts
packages/cdk8s-cli/package.json
packages/cdk8s-cli/test/codegen-types.test.ts
packages/cdk8s-cli/test/integration.test.ts
yarn.lock

- fixed error with pacmak invocation
- added @types/node as a regular dependency so it can be found at runtime
- hide stdout
- remove staging directory

chore: fixes to "import python"

---

packages/cdk8s-cli/bin/cdk8s.ts
packages/cdk8s-cli/bin/cmds/import.ts
packages/cdk8s-cli/bin/cmds/init.ts
packages/cdk8s-cli/bin/cmds/synth.ts
packages/cdk8s-cli/lib/config.ts
packages/cdk8s-cli/lib/import.ts
packages/cdk8s-cli/package.json
packages/cdk8s-cli/test/integration.test.ts

Allow specifying certain switches through a local `cdk8s.yaml` file:
- `app` describes the command to run for `cdk8s synth`
- `language` is the language to use for `cdk8s import`
- `imports` lists all the api sources to import
- `output` can be used to specify the synth output directory
Here is an example for a python project:
```yaml
language: python
app: pipenv run ./main.py
imports:
- k8s@1.14.0
```
Resolves #42

feat(cli): cdk8s.yaml

---

packages/cdk8s-cli/bin/cmds/init.ts
packages/cdk8s-cli/templates/typescript-app/.hooks.sscaff.js

When using a pre-release version of the CLI, use a pinned versions of cdk8s and cdk8s-cli in the newly created package.json instead of caret versions. Otherwise, npm will select the @latest disc-tag instead.

fix(cli): new typescript apps cannot be created with @next versions

---

.github/workflows/build.yml
.github/workflows/release-next.yml
.github/workflows/release.yml
test/README.md
test/run-against-dist
test/test-all.sh
test/test-python-app/expected/test.k8s.yaml
test/test-python-app/main.py
test/test-python-app/test.sh
test/test-typescript-app/expected/test.k8s.yaml
test/test-typescript-app/main.ts
test/test-typescript-app/test.sh

Introduces an integration test harness which can execute arbitrary tests against the build artifacts created under "dist".
Adds a workflow stage to execute these tests during CI builds and releases.

chore: integration tests

---

packages/cdk8s/lib/api-object.ts
packages/cdk8s/lib/chart.ts
packages/cdk8s/lib/testing.ts
packages/cdk8s/test/__snapshots__/chart.test.js.snap
packages/cdk8s/test/chart.test.ts

To simplify interoperability, expose `toJson()` methods on `ApiObject` and on `Chart` which render the Kubernetes JSON for the resource/chart.
Related to #48

feat: chart.toJson() and apiObject.toJson()

---

packages/cdk8s/lib/names.ts
packages/cdk8s/test/names.test.ts

To improve interoperability of cdk8s with other frameworks, do not impose DNS_LABEL constraints on construct names. Instead, normalize them to DNS_LABEL in case they don't comply.
Related to #48

feat: allow arbitrary construct names

---

packages/cdk8s/lib/api-object.ts
packages/cdk8s/lib/chart.ts
packages/cdk8s/test/api-object.test.ts

Allow specifying a default namespace when defining a chart. This namespace will be used for all API objects that do not have an explicit namespace defined.

feat: default namespaces for charts

---

.github/workflows/release.yml
package.json
tools/release.sh
yarn.lock

Fixes https://github.com/awslabs/cdk8s/issues/35
Rather than doing this in the Github actions scripts, we can use [`concurrently`](https://github.com/kimmobrunfeldt/concurrently) to run our release scripts in `package.json` in parallel.
Also removes `/tools/release.sh` as this change replaces that now.

chore: release to all package managers in parallel

---

.github/workflows/release-next.yml
.github/workflows/release.yml
examples/crd/package.json
examples/hello/package.json
examples/podinfo/package.json
examples/web-service/package.json
package.json
packages/cdk8s-cli/bin/cmds/init.ts
packages/cdk8s-cli/package.json
packages/cdk8s-cli/templates/python-app/Pipfile
packages/cdk8s-cli/templates/typescript-app/.hooks.sscaff.js
packages/cdk8s-cli/test/import/__snapshots__/import-crd.test.js.snap
packages/cdk8s/package.json
yarn.lock

chore: upgrade jsii & constructs (#80)
Upgrade jsii to 1.1.0 and constructs to 2.0.0 (which is compatible with jsii 1.x).
BREAKING CHANGE: please upgrade your dependency requirement for "constructs" to ^2.0.0

chore: upgrade jsii & constructs

---

.github/workflows/release-next.yml
CHANGELOG.md
package.json

First commit should fix broken release@next script.
Second commit is to bump up version due to latest breaking changes in https://github.com/awslabs/cdk8s/commit/f917e0a29490eb0369d4583a7303f1fded7f6693

chore: fix release-next script and bump version

---

.github/workflows/release-next.yml
.github/workflows/release.yml

Fixes https://github.com/awslabs/cdk8s/issues/76
Only runs release scripts if on the `awslabs/cdk8s` repository.

chore(gha): prevent gha from running on forks

---

examples/crd/__snapshots__/index.test.js.snap
examples/crd/index.ts

Recent [commit](https://github.com/jenkinsci/kubernetes-operator/commit/110b750ab3361d0ad1dfc57c3cee807a6e088317) to the Jenkins operator that we are using in `crd` example make `master` required.
Looks like that CRD isn't changed all that often, I think it's okay to just update our examples whenever they make breaking changes over there.

chore: fix broken build with updated jenkins crd

---

.github/workflows/build.yml

Updating github build workflow script to just use `yarn integ`. 
This aligns with the release workflows, and lets us change the underlying integ scripts in just one place (`package.json`)

chore(gha): use yarn integ for build integ script

---

examples/crd/package.json
examples/hello/package.json
examples/podinfo/package.json
examples/web-service/package.json
packages/cdk8s-cli/package.json
packages/cdk8s/package.json
yarn.lock

In jsii 1.2.0 the way python code loads jsii tarballs has been changed and is no longer "portable" in a sense that we can harvest the python code into a user-defined location in the cdk8s project (e.g. `imports`).
Until this is fixed, we are pinning jsii to 1.1.0.
jsii bug: https://github.com/aws/jsii/issues/1501

chore(build): pin jsii to 1.1.0 due to bug in 1.2.0

---

packages/cdk8s-cli/lib/import/crd.ts
packages/cdk8s-cli/lib/util.ts

Successfully imports a CRD using `cdk8s import http://0.0.0.0:8000/crd.yml`

fix(crd): import a CRD from an insecure server

---

packages/cdk8s-cli/README.md

Updates the `cdk8s-cli` readme with some of the recent changes to importing.
Fixes: https://github.com/awslabs/cdk8s/issues/28

fix(readme): missing information about imports in cdk8s-cli readme

---

packages/cdk8s-cli/lib/util.ts

Looks like sometimes Github artifacts redirect... for example:
https://github.com/knative/serving/releases/download/v0.14.0/serving-crds.yaml 
--> 
https://github-production-release-asset-2e65be.s3.amazonaws.com/118828329/3c637300-7e2d-11ea-8546-4be9f0554e5b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20200502%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200502T045903Z&X-Amz-Expires=300&X-Amz-Signature=2024809ec2f7868b96eae650106117f9c6a00b9f8d21a2c1827c201013f507e6&X-Amz-SignedHeaders=host&actor_id=0&repo_id=118828329&response-content-disposition=attachment%3B%20filename%3Dserving-crds.yaml&response-content-type=application%2Foctet-stream
---
As far as testing goes.. got as far as `TypeError: Cannot read property 'kind' of null` (from …

fix(redirect): Handle 302 redirect case when importing from remote url

---

test/test-imports/python/cdk8s.yaml
test/test-imports/typescript/cdk8s.yaml

Otherwise we will have a non-deterministic test when the CRD changes

chore(test): pin CRDs in integ test to a specific commit

---

lerna.json
package.json

Recent changes to the `examples/` directory stopped building the example packages.
This fixes that.
Also described here: https://github.com/awslabs/cdk8s/pull/175
```
Lerna package globbing is overridden by yarn workspaces, so removed that and fixed globbing there. Docs - https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
```

chore: fix lerna build globbing

---

packages/cdk8s-cli/bin/cmds/import.ts

Fixes https://github.com/awslabs/cdk8s/issues/185

chore: remove message that named imports are not supported in python

---

CHANGELOG.md
package.json

To be pushed after https://github.com/awslabs/cdk8s/pull/186
Cutting a release here solves https://github.com/awslabs/cdk8s/issues/185 which is asking for named imports support in Python.
Support was added in https://github.com/awslabs/cdk8s/commit/327ba47524b7dfdb05096bb9a78c9d504db4a02c but this has been since the latest release of `0.21.0`

chore(release): 0.22.0

---

.github/semantic.yml

So bumping version with [standard-version](https://github.com/conventional-changelog/standard-version#readme) passes the semantic pull request check :)

chore: allow release scope for semantic releases

---

packages/cdk8s/lib/_util.ts
packages/cdk8s/test/util.test.ts

We used to remove all empty objects and array from synthesized objects. This is a problem in the k8s world since empty objects are sometimes used to represent a value.
For example, the [`volumes.emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) field.

fix(lib): unable to express empty objects and array

---

packages/cdk8s-cli/README.md
packages/cdk8s-cli/lib/import/crd.ts
packages/cdk8s-cli/lib/import/k8s.ts
packages/cdk8s-cli/lib/util.ts
packages/cdk8s-cli/test/import/import-crd.test.ts

Add support for importing YAMLs with `List` resources that contain CRD resources.
This means that you can now do this in order to import all CRDs from a running cluster:
kubectl get crds -o json | cdk8s import /dev/stdin
Fixes #197

feat(cli): import CRDs from a running cluster

---

packages/cdk8s-cli/lib/import/type-generator.ts
packages/cdk8s-cli/test/import/__snapshots__/type-generator.test.js.snap
packages/cdk8s-cli/test/import/type-generator.test.ts
test/test-imports/python/expected-from-config/k8s/__init__.py
test/test-imports/typescript/expected-from-config/k8s.ts

When a JSON schema includes an `enum` string value list, generate a typescript `enum` to offer usability.
Resolves #196
BREAKING CHANGE: enum string values are now proper enums instead of just `string`s.

feat(cli): import - support enum string fields

---

packages/cdk8s-cli/lib/import/type-generator.ts
packages/cdk8s-cli/test/import/__snapshots__/type-generator.test.js.snap
packages/cdk8s-cli/test/import/type-generator.test.ts

We currently only support `anyOf` and `oneOf` that include a list of type names by generating a union-like class.
Modify the generator such that if it cannot parse the schema, it will continue to evaluate it and generate types based on other aspects such as struct specification.
Fixes #171

fix(cli): unable to import CRDs with non-trivial "xxxOf" constraints

---

packages/cdk8s-cli/lib/import/type-generator.ts
packages/cdk8s-cli/test/import/type-generator.naming.test.ts
test/test-imports/python/expected-from-config/k8s/__init__.py
test/test-imports/typescript/expected-from-config/k8s.ts

jsii requires that class names will not be all-caps. This means that a class name like `VPC` is not allowed. To address this, we convert all TLAs to pascal case (i.e. `Vpc`).
Add a unit test for type name normalization.
Fixes #209

fix(cli): unable to import types with all-caps TLAs

---

docs/getting-started/python.md

Strictly speaking, any python `3.7.X` version should work, however, we've seen [issues](https://github.com/awslabs/cdk8s/issues/166) when using the **stock** python 3.7.3 version of MacOS. 
Those issues were resolved when upgrading to `3.7.7`, which is the latest *bugfix* release of the `3.7` minor version line. 
This PR bumps the minimum python version requirement in the getting started to `3.7.7`, as more of a safe-guard than anything else.  

chore: bump min python version to 3.7.7

---

.mergify.yml

Fixes things like this PR: https://github.com/awslabs/cdk8s/pull/221
So that approvals get dismissed with PR updates.
Rule: https://doc.mergify.io/actions.html#dismiss-reviews
Another example here: https://github.com/aws/aws-cdk/blob/master/.mergify.yml#L63

chore: add mergify dismiss_reviews rule

---

.github/workflows/codeql.yml

Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.
Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 
If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

chore: add CodeQL security scanning

---

examples/java/hello/pom.xml
examples/java/hello/src/main/java/com/mycompany/app/HelloKube.java
packages/cdk8s-cli/lib/import/base.ts

As discussed offline, we want java imports to fall under `/src/main/java`. This PR does 2 things:
1. Fixes the outdir for java, so new file structure looks like this:
```
├── src
|  └── main
|     ├── java
|     |  ├── com
|     |  |  └── mycompany
|     |  └── imports
|     |     └── k8s
|     └── resources
|        └── imports
|           └── k8s
```
and you import with `import imports.k8s`
2. Also simplifies the `pom.xml`, with no need for maven magic

fix: move output of java imports into /src/main/java

---

tools/align-version.js
tools/align-version.sh

Pre-release support broke when introducing the new `align-version` script since it didn't support a version suffix.

chore: resurrect pre release support

---

package.json
tools/align-version.js
tools/align-version.sh
yarn.lock

Pre releases do not support caret dependencies.
This means that `^0.25.0-pre1` doesn't actually intersect with `0.25.0-pre1`. This causes a build failure after the `align-version` script has executed for pre-releases:
```console
Declared dependency on version ^0.25.0-pre.cd2871bf17b461d4c707438689eddf433a860847 of cdk8s, but version 0.25.0-pre.cd2871bf17b461d4c707438689eddf433a860847 was found
```
This PR makes the `align-version.js` script aware of pre-releases and only use pinned versions for those dependencies. 

chore: pin pre release dependencies

---

packages/cdk8s-plus/API.md
packages/cdk8s-plus/README.md
packages/cdk8s-plus/package.json
packages/cdk8s-plus/src/deployment.ts
packages/cdk8s-plus/src/job.ts
packages/cdk8s-plus/src/pod.ts
packages/cdk8s-plus/src/service.ts
packages/cdk8s-plus/test/deployment.test.ts
packages/cdk8s-plus/test/job.test.ts
packages/cdk8s-plus/test/pod.test.ts
packages/cdk8s-plus/test/service.test.ts
yarn.lock

Inputs are now pure structs and resources exposes an API class over that struct for mutations.
Also upgraded `jsii-release` version to fix multi package maven publishing

chore(cdk8s+): replace spec classes input with interfaces

---

packages/cdk8s-plus/.projenrc.js
packages/cdk8s-plus/package.json

We still want to ensure that tests do not take a dependency on `lib/`, so the `rm -fr lib/` is relevant. We just want to *also* recompile if all tests pass to make sure we still have build artifacts.
Not super efficient, but good for now.
---

chore(cdk8s+): compile after running tests to restore lib/ directory

---

examples/java/hello/package.json
examples/python/crd/package.json
examples/python/hello/package.json
examples/python/web-service/package.json
examples/typescript/crd/package.json
examples/typescript/hello/package.json
examples/typescript/include-dashboard/package.json
examples/typescript/podinfo/package.json
examples/typescript/web-service/package.json
package.json
packages/cdk8s-cli/package.json
packages/cdk8s-plus/.projenrc.js
packages/cdk8s-plus/package.json
packages/cdk8s/package.json
yarn.lock

Using a caret dependency in a module built with `jsii < 1.3.2` results in an invalid version range in the package manifest file for dotnet artifacts:
See: `[2.0.1, 3.0.0-0)`
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
<metadata>
<id>Org.Cdk8s</id>
<version>0.25.0</version>
<authors>Amazon Web Services</authors>
<owners>Amazon Web Services</owners>
<requireLicenseAcceptance>false</requireLicenseAcceptance>
<license type="expression">Apache-2.0</license>
<licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
<description>Cloud Development Kit for Kubernetes (Stability: Experimental)</description>
<tags>cdk kubernetes k8s constructs</tags>
<repository type="git" url="https://github.com/awslabs/cdk8s.git" /> …
```

chore: pin constructs dep

---

package.json
yarn.lock

Bumping to get a fix for nuget publishing: https://github.com/eladb/jsii-release/pull/7

chore: bump jsii-release to 0.1.9

---

packages/cdk8s-cli/lib/import/base.ts

Fixes https://github.com/awslabs/cdk8s/issues/234
Replace `/` with `.`
Tested locally with the CRD example I'm writing for Java.

fix: java importing crd fails

---

packages/cdk8s-plus/test/pod.test.ts
packages/cdk8s-plus/test/secret.test.ts
packages/cdk8s/src/names.ts
packages/cdk8s/test/names.test.ts

For better readability, now omit adjacent duplicate components when generating resources names. Something like `redrive-redrive-app-configmap-e2d51b95` becomes `redrive-app-configmap-e2d51b95`.
Resolves https://github.com/awslabs/cdk8s/issues/236
BREAKING CHANGE: resource names will now be rendered differently, omitting adjacent duplicate components.

feat(lib): omit duplicate components in generated names

---

.gitattributes

Fixes https://github.com/awslabs/cdk8s/issues/260
Alternatively, we can ignore paths like `examples` and all the various test directories using 
https://github.com/github/linguist#vendored-code
like:
```
examples/* linguist-vendored
```

chore: ignore python for repository linguist analysis

---

packages/cdk8s-cli/src/import/base.ts

Small thing... noticed it was missing `Language.JAVA`... then noticed it's altogether unneeded. Simple cleanup task.

chore: cleanup unused LANGUAGES list in import base

---

examples/python/crd/main.py
examples/python/crd/version.yaml
packages/cdk8s-cli/src/import/base.ts
packages/cdk8s-cli/test/import/__snapshots__/import-crd.test.ts.snap
test/test-imports/python/expected-from-cli/mattermost/com/clusterinstallation/__init__.py
test/test-imports/python/expected-from-cli/mattermost/com/clusterinstallation/_jsii/__init__.py
test/test-imports/python/expected-from-config/jenkins/io/jenkins/__init__.py
test/test-imports/python/expected-from-config/jenkins/io/jenkins/_jsii/__init__.py
test/test-imports/python/expected-from-config/k8s/__init__.py
test/test-imports/python/expected-from-config/k8s/_jsii/__init__.py
test/test-imports/python/expected-from-config/mattermost/mattermost/com/clusterinstallation/__init__.py
test/test-imports/python/expected-from-config/mattermost/mattermost/com/clusterinstallation/_jsii/__init__.py
test/test-imports/python/expected-from-config/stable/example/com/crontab/__init__.py
test/test-imports/python/expected-from-config/stable/example/com/crontab/_jsii/__init__.py
test/test-imports/python/expected-named-from-cli/mattermost/mattermost/com/clusterinstallation/__init__.py
test/test-imports/python/expected-named-from-cli/mattermost/mattermost/com/clusterinstallation/_jsii/__init__.py

With new changes in `jsii-srcmak`, it throws an Error when trying to use a package or moduleName with a hyphen (see commit: https://github.com/aws/jsii-srcmak/commit/766de96d655463dadf5a9578ba38d47121be447b)
This is the other side of that and fixes that issue by replacing `-` with `_`.
Tested by changing the `version.yaml` in the python CRD example to use a hyphen in the name. It successfully comes in as an underscore and is able to be imported.
Fixes https://github.com/awslabs/cdk8s/issues/274

fix(cli): Conform python and java package names to language standards (no hyphens)

---

packages/cdk8s-cli/templates/java-app/cdk8s.yaml

Noticed that the template creates the class `Main.java` but we point to `HelloKube.java` here. Fixing that.

chore: Update java init template typo in class name

---

website/layouts/index.html

Added the same privacy links we added to the [cdkworkshop](https://cdkworkshop.com) according to this [commit](https://github.com/aws-samples/aws-cdk-intro-workshop/commit/33e139605c8ee863e03e6a8e4deef8829fee0348).
Also, removed GoogleAnalytics integration for now until we sort out cookie consent issues.
Here is how the footer looks like now:

chore: privacy compliance

---

packages/cdk8s-cli/package.json
packages/cdk8s-cli/test/import/__snapshots__/import-crd.test.ts.snap
yarn.lock

Upgrades jsii-srcmak version to mitigate security advisory in
`yargs-parser` transient dependency.

chore: upgrade jsii-srcmak version

---

CHANGELOG.md
lerna.json

See [CHANGELOG](https://github.com/awslabs/cdk8s/blob/bump/0.29.0/CHANGELOG.md)

chore(release): 0.29.0

---

packages/cdk8s-plus/README.md
packages/cdk8s-plus/src/imports/k8s.ts

chore(plus): bump k8s imports to 1.17.0

---

.github/closed-issue-message.yml

- Add a Github Action which sets a default message that will be commented on all issues when they get closed to warn users that comments on closed issues are hard for our team to see.
This is an OSDS effort across all SDKs&Tools repos to address the issue of customers expecting a response from AWS when they comment on closed issues.
By setting this default message we are clarifying expectations and explaining Github's limitation instead of letting users assume we are willfully ignoring them. We are giving clear directives about how to notify us and we're giving customers agency to make their own informed decisions as to whether or not they want to comment on closed issues.
---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 …

chore: add closed issue message github action

---

packages/cdk8s/test/app.test.ts

The code previously created a temp directory name that was
a sibling of the os.tempdir(). This required write access to
the directory instead of simply write access to the tmpdir.

fix: allow tests to run without write access to os.tmpdir parent

---

docs/getting-started/typescript.md
examples/typescript/cdk8s-plus-elasticsearch-query/__snapshots__/main.test.ts.snap
examples/typescript/podinfo/lib/deployment.ts
examples/typescript/web-service/web-service.ts
packages/cdk8s-plus/src/deployment.ts
packages/cdk8s-plus/test/deployment.test.ts
packages/cdk8s/API.md
packages/cdk8s/src/app.ts
packages/cdk8s/src/dependency.ts
packages/cdk8s/src/index.ts
packages/cdk8s/src/names.ts
packages/cdk8s/test/dependency.test.ts
packages/cdk8s/test/names.test.ts

`Node.of(construct).uniqueId` is bound to CloudFormation's resource logical ID rule, which is not strictly compatible with the K8s label rule. It might lead to invalid K8s manifests.
I've changed all `Node.of(construct).uniqueId` with `Node.of(construct).path`, or `Names.toDnsLabel(Node.of(construct).path)` if needed.
Since K8s DNS label rule are subset of label key name segment/value rule, I've added `Names.toLabelValue` and used it for selector labels.
fixes: #323
BREAKING CHANGE: cdk8s-plus's value of a label `cdk8s.deployment` of Pods are changed

fix(lib): `uniqueId` is not compatible with the k8s labels

---

packages/cdk8s-plus/README.md
packages/cdk8s/src/names.ts
packages/cdk8s/test/names.test.ts

Sometimes names generated from paths include empty components like `service/test-router-runtime---hello-pod-a611028d`. This change removes duplicate hyphens.
BREAKING CHANGE: auto-generated resource names that included duplicate hyphens will change will be replaced when applied.

fix(lib): duplicate hyphens in generated resource names

---

examples/typescript/cdk8s-plus-elasticsearch-query/main.ts
examples/typescript/cdk8s-plus-ingress/main.ts
packages/cdk8s-plus/API.md
packages/cdk8s-plus/src/deployment.ts
packages/cdk8s-plus/src/service.ts
packages/cdk8s-plus/test/deployment.test.ts
packages/cdk8s-plus/test/service.test.ts

Introduce `service.addDeployment()` which associates a deployment to a service. The method `deployment.expose()` now just delegates the work to this method.
Additionally, the logic that added the selector label to the deployment was moved from `deployment._toKube()` into `service.addDeployment()` and combined with the logic that installed the selector on the service (which is much more natural).
BREAKING CHANGE: `deployment.expose()` now takes `port` as a positional argument (before: `deployment.expose({ port })`, now: `deployment.expose(port)`).

feat(plus): service.addDeployment()

---

packages/cdk8s-plus/API.md
packages/cdk8s-plus/README.md
packages/cdk8s-plus/src/container.ts
packages/cdk8s-plus/src/index.ts
packages/cdk8s-plus/src/probe.ts
packages/cdk8s-plus/test/container.test.ts
packages/cdk8s-plus/test/probe.test.ts

Adds support for container-level readiness probes.

feat(plus): readiness probes

---

packages/cdk8s/API.md
packages/cdk8s/README.md
packages/cdk8s/src/api-object.ts
packages/cdk8s/src/chart.ts
packages/cdk8s/test/api-object.test.ts

Allow specifying `labels` when defining charts and those will be applied to all API objects within this chart.

feat: chart-level labels

---

packages/cdk8s-plus/API.md
packages/cdk8s-plus/README.md
packages/cdk8s-plus/src/container.ts
packages/cdk8s-plus/test/container.test.ts

This PR expands the probe support in Container to include liveness and startup probes.

feat(plus): add liveness and startup probes to Container

---

packages/cdk8s-plus/API.md
packages/cdk8s-plus/src/deployment.ts
packages/cdk8s-plus/src/service.ts
packages/cdk8s-plus/test/deployment.test.ts

This PR expands the `Deployment expose()` method to allow users to fully specify options to the generated Service and Port.  Originally I created this so I could provide a user defined name for the Service through metadata.  In the process I also found the need to allow specifying the port details for name and protocol.

feat(plus): expose service options in `expose()`

---

docs/plus/index.md
packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js

Apparently by default PyPI doesn't offer pre-releases on installation, and in fact doesn't treat the `0.x` version line as a pre-release as well. This means that as far as PyPI is concerned, `0.33.0` is our latest version, and is more stable than `1.0.0b`.
This breaks our init template:
```console
Building requirements...
Resolving dependencies...
✘ Locking Failed!
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2020.5.28/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2020.5.28/libexec/lib/python3.8/site-packages/pipenv/resolver.py", line 753, in resolve_packages
[ResolutionFailure]: …
```

fix(cli): python init templates are broken

---

packages/cdk8s-cli/src/cli/cmds/import.ts
packages/cdk8s-cli/src/import/crds-dev.ts
packages/cdk8s-cli/src/import/dispatch.ts
packages/cdk8s-cli/test/import/__snapshots__/import-crds-dev.test.ts.snap
packages/cdk8s-cli/test/import/fixtures/crds-dev/github-crossplane-crossplane-v0.14.0.yaml
packages/cdk8s-cli/test/import/import-crd.test.ts
packages/cdk8s-cli/test/import/import-crds-dev.test.ts
packages/cdk8s-cli/test/import/import-k8s.test.ts
packages/cdk8s-cli/test/import/util.ts

Introduce crds.dev import shortcut: `cdk8s import github:account/repo[@VERSION]`
Example:
`cdk8s import github:crossplane/crossplane@0.14.0`
Resolves #377
In a future PR would like to generate a single module per k8s API group with all CRDs for that API group, so you could:
```ts
import { CompositeResourceDefinition, Composition } from './imports/apiextensions.crossplane.io';
```

feat(cli): import from crds.dev

---

CONTRIBUTING.md

I have found this helpful to run the integration tests on Linux.

feat: add contributor instructions about using jsii docker image

---

packages/cdk8s-cli/src/cli/cmds/init.ts
packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js
test/test-python-app/test.sh

A while back we [included](https://github.com/awslabs/cdk8s/pull/293) installation of `cdk8s-plus` as part of the python init template.
The PR [mentioned](https://github.com/awslabs/cdk8s/pull/293#discussion_r474408225) that this was problematic because `cdk8s-plus` depends on `cdk8s`, and dependency resolution in our integ tests fails since it tries to lookup the current version of `cdk8s` in PyPI, and obviously fails as it has not been published yet.
The solution was to use `--no-deps` flag so that remote dependency resolution won't happen. This was kind of safe because `cdk8s` is explicitly installed prior to `cdk8s-plus`:
https://github.com/awslabs/cdk8s/blob/bb0a5cc0762e753f1f18093b3cd15cbb83bd7c5e/packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js#L33
And by chance, …

fix(cli): python init template doesn't install cdk8s-plus in the correct env

---

docs/getting-started.md

missing closing backticks break the rendering

fix(docs): WebService typescript example formatting

---

packages/cdk8s-plus-17/src/container.ts
packages/cdk8s-plus-17/test/container.test.ts

Add a check for the case where a container is attempted to be built from another container.
Any place that takes ContainerProps actually also accepts Containers. This happens because ContainerProps has all optional properties except image .  Since Container has an a public property image, it gets passed along but that is really the only thing that gets used. 
Problem is that if you pass in a container object, the nested container will not get all the settings, so I don't think this should be allowed.
note: this is a bit of an ugly hack to prevent this.  I was hoping to find a way to do this with the type system but didn't find a solid option without changing some public property names and breaking the API.
*By submitting this pull request, I confirm that my contribution is made under the …

fix(plus-17): don't allow containers to be contructed from containers

---

.github/workflows/release.yml

Closes https://github.com/awslabs/cdk8s/issues/409
Seems like this has been actually failing for a while looking at commit history here: https://github.com/Homebrew/homebrew-core/search?q=cdk8s&type=commits
And other build history in our own repo here: https://github.com/awslabs/cdk8s/runs/1285293264?check_suite_focus=true
I think doing a version-bump after pulling the repo should solve it.

chore: fix versioning for homebrew releases

---

packages/cdk8s-cli/src/util.ts
packages/cdk8s-cli/templates/java-app/.hooks.sscaff.js
packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js

Closes https://github.com/awslabs/cdk8s/issues/414
Looked at these for some more info:
https://superuser.com/questions/207707/what-is-windows-equivalent-of-the-which-command-in-unix-is-there-an-equivale
https://stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js
---
It brings up the larger question though - should the `build` workflow run on Windows? Will the JSII/superchain docker image work on Windows?
---

fix: which command missing for windows

---

packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js

This [PR](https://github.com/awslabs/cdk8s/pull/399) removed the need for `pip3`, but the validation still remained.

chore(cli): remove pip3 validation since its no longer needed

---

packages/cdk8s/src/metadata.ts
packages/cdk8s/test/metadata.test.ts

Allows annotations to be dynamically rendered.

fix: Lazy is not resolved in metadata

---

.github/workflows/dependencies.yml

Apparently PR's created Using the default `secrets.GITHUB_TOKEN` do not trigger workflow executions on them.
This means the PR's currently created by the automatic dependency upgrade will never run CI.
Created a dedicated automation token so that workflows can be triggered.
See https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs

chore(deps): Dedicated automation token

---

.github/workflows/dependencies.yml
packages/cdk8s-cli/package.json
packages/cdk8s-plus-17/package.json
packages/cdk8s/package.json
packages/projen-common.js
yarn.lock

We added transitive dependency updates in this [PR](https://github.com/awslabs/cdk8s/pull/465) by running `yarn upgrade`, but this now also upgrades the modules that we previously rejected from `ncu`.
Added a pattern to reject those modules from yarn as well.
Also moved typescript special casing to projen by using a `~` dependency (instead of `^`) so we stick to the current minor like we want.

chore(deps): Exclude constructs and projen from transitive dependency upgrades

---

.github/workflows/release.yml

To avoid unnecessarily opening PRs with Homebrew-core.

chore(release): skip homebrew release for beta releases

---

packages/cdk8s-plus-17/src/pod.ts
packages/cdk8s-plus-17/test/pod.test.ts

Allow multiple container mounts to use the same volume.
This PR also introduces a restriction for adding two different volumes with the same name to a pod.
Fixes https://github.com/awslabs/cdk8s/issues/483

fix(plus-17): multiple mounts per volume result in duplicate volumes for pod spec

---

packages/cdk8s/src/yaml.ts
packages/cdk8s/test/__snapshots__/yaml.test.ts.snap
test/test-java-app/expected/test.k8s.yaml
test/test-python-app/expected/test.k8s.yaml
test/test-typescript-app/expected/test.k8s.yaml

---
Currently, the output of multiline strings is very ugly in the rendered YAML files; there are many extra newlines and backslashes, majorly hurting readability.
To fix #172, this PR returns to the default YAML string settings that allow the parser to decide between double-quoting or creating a block-literal from a string. 
To ensure we don't bring back the issues from #325, this PR also sets the default YAML schema to `yaml-1.1`, to retain compatibility with most other YAML parsers' default settings.
Aside from the tests in the PR, I have also confirmed this fix against the repro steps in #325.

fix: set yaml default schema to 1.1

---

docs/assets/logos/readme.md

Currently, there is an issue which the logo images doesn't appeared correctly with 404 status code in the websites:
- https://cdk8s.io/docs/v1.0.0-beta.5/assets/logos/readme/
- https://cdk8s.io/docs/latest/assets/logos/readme/
It was occurred because it used incorrect absolute path at *docs/assets/logos/readme.md*, though multiple versions are published at once (e.g. _docs/latest_, _docs/v1.0.0-beta.5_). So this pull request makes it use relative path which can be successfully accessed from multiple versions. (e.g. `/docs/assets/logos/icon/cdk8s.icon.color.png` → `../icon/cdk8s.icon.color.png`)
1. Build docs by `CONTRIBUTING.md`.
1. Run HTTP server on the published …

fix(docs): correct logo paths

---

packages/cdk8s/API.md
packages/cdk8s/src/duration.ts
packages/cdk8s/test/duration.test.ts

As we prepare to release experimental go support for CDK8s, we encountered an issue where `Duration.toIsoString()` and `Duration.toISOString()` conflict when they are converted to Go naming conventions.
Since one of them is deprecated, just remove it.
BREAKING CHANGE: the deprecated API `Duration.toISOString()` has been removed. Use `Duration.toIsoString()` instead.
---

fix(lib): deprecated toISOString() conflicts with toIsoString()

---

packages/cdk8s/src/helm.ts
packages/cdk8s/test/helm.test.ts

With charts such as cert-manager with crds included, the helm import functionality can run into an ENOBUFS error due to insufficient buffer size. This is very similar to issue #363 (except with helm instead of yaml download) and uses a very similar fix to PR #454. Thanks.

fix(lib): ENOBUFS for large helm charts

---

docs/plus/index.md

This pull request resolves #581. It fixes a typo, 'kuberentes' → 'kubernetes'.

docs: fix typo

---

packages/cdk8s/API.md
packages/cdk8s/src/yaml.ts
packages/cdk8s/test/__snapshots__/yaml.test.ts.snap
packages/cdk8s/test/yaml.test.ts

Fix #588 by changing the max line length to 0 (disabled). I've made the choice to add a public stringify to make sure it is testable (without writing to the file system).

fix: multiline string with line greater than 80 chars are malformed

---

docs/cli/import.md

I just found [a broken doc for import](https://cdk8s.io/docs/v1.0.0-beta.10/cli/import/#module-name) when I read the page. 
It is because of the wrong indentation for the code blocks.
I checked it rendered correctly in my local.

fix(docs): correct language tab indentation

---

CONTRIBUTING.md
README.md
docs/concepts/escape-hatches.md
docs/examples/crd.md
docs/examples/hello.md
docs/examples/plus-elasticsearch.md
docs/examples/plus-ingress.md
docs/examples/podinfo.md
docs/examples/web-service.md
docs/support.md
examples/typescript/cdk8s-plus-elasticsearch-query/README.md
mkdocs.yml
research/README.md
website/layouts/index.html

Update organization URL path from `awslabs` to `cdk8s-team` to avoid broken links.

chore: update organization URL path to cdk8s-team

---

.projen/deps.json
.projenrc.js
package.json
yarn.lock

To resolve a bunch of security alerts on transitive deps from lerna.
It seems like the [breaking changes](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes) in 4.x should not affect us

chore: upgrade lerna to 4.x

---

docs/reference/cdk8s-plus-20/go.md
docs/reference/cdk8s-plus-21/go.md
docs/reference/cdk8s-plus-22/go.md

fix: library names in go reference header is wrong

---

docs/getting-started.md

Currently, the instructions for TS mention force the user to run a watch command in order to properly synth the app.
This instruction is easily overlooked since its not intuitive, in addition, it creates a complexity of having to run a background process. 
Skipping this command will make it so running `cdk8s synth` further down the guide will have no affect. 
Instead, we instruct the user to run a `npm run compile && cdk8s synth` command in order to ensure compilation happens. As for running watch, we now mention this in a quote as an option to forgo explicit compilation - but this is not the main path.
Here is how TS will look like following this PR:
In contrast with python for example, where we simply use `cdk8s synth`.

fix(website): TS getting started is not clear enough with relation to synth

---

docs/plus/index.md

As originally written, the Go example in the index page throws an error because id is undefined. This PR fixes the document by defining id and setting it equal to "ubuntu" (since we are creating an ubuntu deployment)

fix(docs): undefined id error on index doc Go section

---

website/layouts/index.html
website/static/css/cdk8s.webflow.css

Signed-off-by: Christopher Rybicki <rybickic@amazon.com>

chore: add link to Construct Hub in navigation menu

---

examples/java/crd/pom.xml
examples/java/hello/pom.xml
examples/java/helm-bitnami/pom.xml
examples/java/web-service/pom.xml

This dependency is not being used, and causing this repo to have a low severity security alert from [CVE-2020-8908](https://github.com/cdk8s-team/cdk8s/security/dependabot/examples/java/crd/pom.xml/com.google.guava:guava/open). So, let's remove it. 
To verify removing this dependency is okay, I built and synth'ed all of the java examples locally.

chore(java examples): remove dependency on com.google.guava:guava

---

.github/workflows/integ.yml
.mergify.yml
.projenrc.js

Supersedes #804
This updates `.projenrc.js` to avoid having to manually override all of `mergify.yml`.
Signed-off-by: Christopher Rybicki <rybickic@amazon.com>

chore: refactor integ tests to use new projen apis

---

docs/plus/index.md

Added a specific example that would cause a poor user experience if we vended a single library.

chore: clarify why cdk8s+ is vended in multiple packages

---

docs/plus/container.md

The API does not have the function `kplus.EnvValue.fromSecret` which was used in example. Changed it to use `kplus.EnvValue.fromSecretValue` instead.

fix: docs refer to non existent `EnvValue.fromSecret` function

---

mkdocs.yml

This PR fixes a bug with tab context boxes which was causing tab context boxes to not render correctly. This also caused multiple page breaking overflow issues.
To fix this I added the required param `alternate_style: true` to `- pymdownx.tabbed:` as mentioned in the [tabbed docs](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed)
I also disabled the header's autohide feature. This is unrelated to the bug. I disabled it because it seemed like it was causing an awkward space between the nav trees and top of page. 
Demo of nav menu overflowing footer
Demo of autohiding header

fix(docs): overflow y-axis bugs

---

docs/build.sh

Unfortunately Linux doesn't support the same sed command format as MacOS. So the website build worked locally but [failed](https://github.com/cdk8s-team/cdk8s/actions/runs/3246855413/jobs/5326489124) in CI after this PR was merged:
- https://github.com/cdk8s-team/cdk8s/pull/1005
This PR replaces use of `sed -i '' ...` with a linux workaround.

fix(docs/bash.sh): linux doesn't support mac `sed -i ''`

---

docs/plus/index.md

Fixes #1035 
The Java example on the [cdk8s+ getting started page](https://cdk8s.io/docs/latest/plus/#getting-started) is incomplete. Currently it is:
```java
import org.cdk8s.App;
import org.cdk8s.Chart;
import org.cdk8s.plus25.Deployment;
import org.cdk8s.plus25.ContainerProps;
App app = new App();
Chart chart = new Chart(app, "Chart");
Deployment.Builder.create(chart, "Deployment")
.replicas(3)
.containers(Arrays.asList(ContainerProps.builder()
.image("ubuntu")
.build()))
.build();
app.synth();
```
This code is incomplete as it will not compile if a user directly copies and pastes it to the `Main.java` file of a new cdk8s java app. I updated the docs with the completed and working code example.

fix(docs): java example in cdk8s+ docs is incomplete

---

docs/getting-started.md

`ConstructOptions` was removed in constructs v10 and we didn't update the docs. 
The code now matches the [example](https://github.com/cdk8s-team/cdk8s-examples/blob/main/go/cdk8s-composition/webservice.go) and properly compiles.
Fixes https://github.com/cdk8s-team/cdk8s/issues/1280

fix(website): incorrect golang code snippets in getting started guide 

---

.github/workflows/build.yml
.github/workflows/upgrade.yml
package.json
yarn.lock

Our upgrade workflow is failing due to a node version mismatch. This has been fixed in [cdk8s projen common](https://github.com/cdk8s-team/cdk8s-projen-common/pull/314) but that update is not going through since update workflow is failing. So this PR updates the library separately.

chore: update cdk8s/projen-common version

---

kubernetes-schemas/v1.27.0/_definitions.json

This PR adds the v1.27.0 Kubernetes spec. This is required in order for us to add a new version to cdk8s-plus.

chore: v1.27.0 kubernetes-spec

---

.github/workflows/upgrade-configuration.yml
.github/workflows/upgrade-dev-dependencies.yml
.github/workflows/upgrade-runtime-dependencies.yml
.projen/tasks.json
package.json
yarn.lock

There was a bug in @cdk8s/projen-common which broke the config upgrade workflow. This requires a manual upgrade to get it working again.
Signed-off-by: Cory Hall <43035978+corymhall@users.noreply.github.com>

chore: manually upgrade @cdk8s/projen-common

---

docs/basics/app.md

- Resolver interface name was wrong. Left over from its previous name
- Replace the example resolver with a slightly more realistic one
- Remove explanation about invocation patterns, its kind of overwhelming and un-necessary now that the example contains a real implementation

chore(website): resolver docs touchups

---

website/layouts/index.html

Following https://github.com/cdk8s-team/cdk8s/pull/1285, the directory was renamed. 
See https://cdk8s.io/docs/latest/get-started/

fix(website): wrong getting started link

---

.github/workflows/bump-latest-cdk8s-plus-library.yml
src/k8s-automation.ts

The `bump-latest-cdk8s-plus-library` workflow is [failing](https://github.com/cdk8s-team/cdk8s/actions/runs/6562478240):
```console
[Invalid workflow file: .github/workflows/bump-latest-cdk8s-plus-library.yml#L171](https://github.com/cdk8s-team/cdk8s/actions/runs/6562478240/workflow)
The workflow is not valid. .github/workflows/bump-latest-cdk8s-plus-library.yml (Line: 171, Col: 13): A sequence was not expected
```
Fix label definition according to action [documentation](https://github.com/actions-ecosystem/action-create-issue).
> The labels which are added to the created issue when it's created. Must be separated with line breaks if there're multiple labels.

fix(workflows): invalid labels in `bump-latest-cdk8s-plus-library`

---

website/build.sh
website/layouts/index.html

The dropdown shows the version of the package instead of the spec number:

fix(website): cdk8s-plus dropdown shows incorrect spec numbers

---

website/layouts/index.html

Follow up to https://github.com/cdk8s-team/cdk8s/pull/1839, which only fixed the links themselves, but not the anchor label.

fix(website): cdk8s-plus dropdown shows version numbers instead of spec numbers

---

docs/reference/index.md

They were using absolute paths instead of relative. 
Fixes https://github.com/cdk8s-team/cdk8s/issues/1958

fix(website): links to cdk8s-core api references are broken
