- README.md
> Fix broken link to the roadmap

- examples/hello/package.json
- examples/podinfo/package.json
- examples/web-service/package.json
- packages/cdk8s-cli/bin/cmds/init.ts
- packages/cdk8s-cli/package.json
- packages/cdk8s/package.json
- yarn.lock
> chore(examples): use 0.0.0 for local dependencies

- CHANGELOG.md
- package.json
> chore(release): 0.13.0

- README.md
> fix(readme): hello example link is broken

- README.md
> chore(readme): Typo for the Hello example

- README.md
- docs/intro-python.md
- docs/intro-typescript.md
Finishes up: https://github.com/awslabs/cdk8s/issues/49
Puts homebrew badge on the README and updates python intro docs to install using `brew install cdk8s`
> chore(readme): Update README with homebrew badge and update intro docs

- examples/web-service/web-service.ts
> fix(examples): "replicas" option is not respected in the web-service example

- packages/cdk8s-cli/bin/cmds/init.ts
- test/test-python-app/test.sh
- test/test-typescript-app/test.sh
As agreed on with @eladb.
Fixes #93
> feat(cli): ignore hidden files in "cdk8s init"

- website/content/getting-started/_index.md
- website/content/getting-started/python.md
- website/layouts/_default/section.html
- website/layouts/shortcodes/button.html
> fix(docs): top-level "getting started" page not found

- examples/crd-python/.gitignore
- examples/crd-python/Pipfile
- examples/crd-python/README.md
- examples/crd-python/cdk8s.yaml
- examples/crd-python/main.py
- examples/crd-python/mattermost_crd.yaml
- examples/crd-python/package.json
Will be useful in ensuring that all python changes are non-breaking.
> feat(examples): using CRDs in python

- README.md
Have a look here: https://github.com/iliapolo/cdk8s/tree/ide-gif
Let me know if you had a different location in mind, I intentionally put it in the beginning of the main `README` as an eye pleaser. 
chore(readme): added a chart authoring git from VS IDE (#135)
Added a GIF that demonstrates IDE assistance during chart authoring
> chore(readme): added a chart authoring gif from VS IDE

- README.md
> chore(readme): Fix dead links

- CHANGELOG.md
- package.json
Bumping up version to release some of the bug fixes.
> chore(release): 0.21.0

- packages/cdk8s-cli/README.md
> chore(readme): fix typo of command name

- docs/getting-started/typescript.md
> chore(example): Fix dead reference

- packages/cdk8s/package.json
Enables snapshot updating from project root. Command:
```
yarn test -- -- -u
```
References:
https://stackoverflow.com/questions/48169878/pass-args-into-lerna-exec-command
https://stackoverflow.com/questions/48202815/sending-custom-arguments-to-npm-yarn-scripts-with-lerna
> chore(lib): make snapshot updating easier by adjusting test script

- .github/workflows/close-stale-issues.yml
- add github action that warns and then closes stale issues
> chore: add close stale issues github action

- CHANGELOG.md
- package.json
> chore(release): 0.23.0

- CHANGELOG.md
- package.json
> chore(release): 0.24.0

- packages/cdk8s-cli/lib/import/crd.ts
- packages/cdk8s-cli/package.json
- packages/cdk8s-cli/templates/python-app/Pipfile
- packages/cdk8s-cli/test/import/import-crd.test.ts
- test/test-imports/python/expected-from-cli/mattermost/com/clusterinstallation/__init__.py
- test/test-imports/python/expected-from-cli/mattermost/com/clusterinstallation/_jsii/__init__.py
- test/test-imports/python/expected-from-config/jenkins/io/jenkins/__init__.py
- test/test-imports/python/expected-from-config/jenkins/io/jenkins/_jsii/__init__.py
- test/test-imports/python/expected-from-config/k8s/__init__.py
- test/test-imports/python/expected-from-config/k8s/_jsii/__init__.py
- test/test-imports/python/expected-from-config/mattermost/mattermost/com/clusterinstallation/__init__.py
- test/test-imports/python/expected-from-config/mattermost/mattermost/com/clusterinstallation/_jsii/__init__.py
- test/test-imports/python/expected-from-config/stable/example/com/crontab/__init__.py
- test/test-imports/python/expected-from-config/stable/example/com/crontab/_jsii/__init__.py
- test/test-imports/python/expected-named-from-cli/mattermost/mattermost/com/clusterinstallation/__init__.py
- test/test-imports/python/expected-named-from-cli/mattermost/mattermost/com/clusterinstallation/_jsii/__init__.py
- yarn.lock
> chore: upgrade dependencies

- CHANGELOG.md
- package.json
> chore(release): 0.25.0

- packages/cdk8s-cli/package.json
- yarn.lock
Includes a bugfix required for #233 and #117 
> chore: update jsii-srcmak to ^0.1.4

- .github/workflows/codeql.yml
> chore: codeql build for java

- CHANGELOG.md
- lerna.json
- tools/bump.sh
> chore(release): v0.26.0

- packages/cdk8s-plus/README.md
> chore(plus): Basic Installation guide for python and typescript

- packages/cdk8s-cli/package.json
- yarn.lock
> chore: Upgrade json2jsii to 0.1.4

- CHANGELOG.md
- lerna.json
> chore(release): 0.27.0

- examples/python/crd/Pipfile
- examples/python/hello/Pipfile
- examples/python/web-service/Pipfile
> fix(examples): Add missing dependencies on python examples.

- packages/cdk8s-cli/templates/python-app/.hooks.sscaff.js
- test/test-imports/python/expected-from-cli/mattermost/com/clusterinstallation/__init__.py
- test/test-imports/python/expected-from-config/jenkins/io/jenkins/__init__.py
- test/test-imports/python/expected-from-config/k8s/__init__.py
- test/test-imports/python/expected-from-config/mattermost/mattermost/com/clusterinstallation/__init__.py
- test/test-imports/python/expected-named-from-cli/mattermost/mattermost/com/clusterinstallation/__init__.py
> chore: update integ tests and python scaffolding

- README.md
This PR adds information about the cdk8s community meeting the the README.
Signed-off-by: Eddie Zaneski <eddiezane@gmail.com>
> feat: Add community meeting to README

- README.md
- docs/getting-started/java.md
- website/config.yaml
- website/layouts/index.html
Getting started docs for Java.
> chore(docs): Getting-started doc for java

- CHANGELOG.md
- lerna.json
> chore(release): 0.28.0

- CHANGELOG.md
- lerna.json
See [CHANGELOG](https://github.com/awslabs/cdk8s/blob/bump/0.30.0/CHANGELOG.md)
> chore(release): 0.30.0

- README.md
- website/layouts/index.html
> feat: migrate to cdk.dev slack workspace

- packages/cdk8s/src/_loadurl.js
The code in `_loadurl.js` which reads manifests from files did not wait until the entire input was written to stdout before it exited.
The fix is not to `exit(0)` but rather just let node exit gracefully.
> fix(lib): corrupted manifests when including large files

- .mergify.yml
- packages/cdk8s-plus/src/probe.ts
Also applied comment from https://github.com/awslabs/cdk8s/pull/353#pullrequestreview-512454563 which i suspect didn't have a change to be addressed because of this. 
> chore: make mergify consider `do-not-merge` label

- packages/cdk8s-cli/src/import/k8s.ts
- packages/cdk8s-plus/src/imports/k8s.ts
Follow up to https://github.com/awslabs/cdk8s/pull/382
> chore: cli to use our repo for k8s imports

- docs/plus/index.md
> chore: rephrase terminology

- packages/cdk8s-cli/src/cli/cmds/init.ts
- website/layouts/index.html
cdk8s-plus api reference link from the main page was broken.
And the name of the link to the cli was funky.
> chore: some broken links

- CHANGELOG.md
- lerna.json
See [CHANGELOG](https://github.com/awslabs/cdk8s/blob/benisrae/beta.2/CHANGELOG.md)
> chore(release): 1.0.0-beta.2

- CHANGELOG.md
- lerna.json
See [CHANGELOG](https://github.com/awslabs/cdk8s/blob/bump/1.0.0-beta.3/CHANGELOG.md)
> chore(release): 1.0.0-beta.3

- docs/getting-started.md
Closes https://github.com/awslabs/cdk8s/issues/386
Tested locally, now if you copy + paste the example here it should all compile.
> chore(docs): TS getting started doesn't compile

- docs/getting-started.md
Fixes https://github.com/awslabs/cdk8s/issues/406
Fixes https://github.com/awslabs/cdk8s/issues/386
> fix(docs): align getting started with new code

- CHANGELOG.md
- lerna.json
> chore(release): 1.0.0-beta.4

- docs/cli/installation.md
- packages/cdk8s-cli/README.md
closes https://github.com/awslabs/cdk8s/issues/409
> chore(docs): update docs to indicate old version of cli in homebrew

- packages/cdk8s-cli/package.json
- packages/cdk8s-cli/test/import/__snapshots__/import-crd.test.ts.snap
- packages/cdk8s-cli/test/import/__snapshots__/import-crds-dev.test.ts.snap
- packages/cdk8s-plus-17/.projen/deps.json
- packages/cdk8s-plus-17/.projenrc.js
- packages/cdk8s-plus-17/package.json
- packages/cdk8s/.projen/deps.json
- packages/cdk8s/.projenrc.js
- packages/cdk8s/package.json
- yarn.lock
Initial step to produce golang bindings for cdk8s and cdk8s-plus-17.
> chore: build go bindings

- OWNERS.md
resolves #449 as part of https://github.com/cncf/toc/issues/556
> chore: add owners file

- test/test-imports/python/expected-from-cli/com/mattermost/__init__.py
- test/test-imports/python/expected-from-config/com/example/stable/__init__.py
- test/test-imports/python/expected-from-config/io/jenkins/__init__.py
- test/test-imports/python/expected-from-config/k8s/__init__.py
- test/test-imports/python/expected-from-config/mattermost/com/mattermost/__init__.py
- test/test-imports/python/expected-named-from-cli/mattermost/com/mattermost/__init__.py
> chore: update python integ tests

- CHANGELOG.md
- lerna.json
> chore(release): 1.0.0-beta.9

- README.md
> chore: Update community meetings schedule

- CHANGELOG.md
- lerna.json
> chore(release): 1.0.0-beta.10

- .github/workflows/release.yml
- CHANGELOG.md
- lerna.json
> chore(release): 1.0.0-beta11

- packages/cdk8s-plus-17/package.json
- packages/cdk8s/.projenrc.js
> chore(go): Use cdk8s-team org in module name

- docs/concepts/helm.md
> fix(docs): typo of helm doc

- examples/java/hello/pom.xml
- examples/java/web-service/pom.xml
Resolves dependabot alerts:
- https://github.com/cdk8s-team/cdk8s/security/dependabot/examples/java/web-service/pom.xml/com.google.guava:guava/open
- https://github.com/cdk8s-team/cdk8s/security/dependabot/examples/java/hello/pom.xml/com.google.guava:guava/open
> chore(examples): update guava version to 30.0 

- .github/workflows/website.yml
- .projenrc.js
Setup the correct Node.js version in the workflow
> chore(website): setup node 14

- .github/workflows/website.yml
- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- yarn.lock
> chore(website deployment): install node dependencies

- docs/getting-started.md
> docs: add getting started for Go

- docs/concepts/api-object.md
- docs/concepts/deps.md
> docs: update docs to use class prefixes

- kubernetes-schemas/v1.22.0/_definitions.json
Generated using import-spec.sh.
----
> chore: k8s schema for v1.22.0

- docs/plus/index.md
Resolves https://github.com/cdk8s-team/cdk8s/issues/683
> feat: Golang and Java getting started for cdk8s-plus

- docs/cli/synth.md
As mentioned by @Chriscbr on https://github.com/cdk8s-team/cdk8s-core/pull/297
I thought about this over the weekend and I think this is in the spirit of what you were asking, let me know, I'm happy to make any changes.
> feat: Update synth docs to reference AppProps for YAML output config

- examples/python/crd/Pipfile
- examples/python/hello/Pipfile
- examples/python/hello/main.py
- examples/python/helm-bitnami/Pipfile
- examples/python/web-service/Pipfile
- examples/python/web-service/webservice.py
Our python examples were wildly out of date. 
Signed-off-by: iliapolo <epolon@amazon.com>
> chore: update python examples

- kubernetes-schemas/v1.24.0/_definitions.json
Signed-off-by: iliapolo <epolon@amazon.com>
> feat(kubernetes-schemas): schema for `1.24.0`

- docs/getting-started.md
just a typo fix in the getting started guide.
Signed-off-by: ks6088ts <ks6088ts@gmail.com>
> chore: fix typos of several words

- docs/plus/network-policy.md
- docs/plus/pod.md
Resolves https://github.com/cdk8s-team/cdk8s-plus/issues/1113
Signed-off-by: iliapolo <epolon@amazon.com>
> chore(docs): `portNumber` instead of `port`

- docs/plus/index.md
Signed-off-by: Eli Polonsky <epolon@amazon.com>
> chore(website): misplaced version number for cdk8s-plus

- ADOPTERS.md
And some other touchups
Signed-off-by: Eli Polonsky <epolon@amazon.com>
> chore(adopters): mention cdk.dev slack channel

- OWNERS.md
> chore(owners): https://github.com/ryparker

- ADOPTERS.md
@iliapolo asked if we would be OK being on the adopters list. I've run it by our CTO, and it's a 👍, so here's the PR.
I also fixed the alphabetisation and made a slight grammar change. That's a separate commit so can be easily binned if desired.
> chore(adopters): https://griffin.com

- README.md
Our mailing list is not active at the moment as well as the community meetings. We are reworking them towards a relaunch.
> chore: cleanup community resources

- OWNERS.md
Remove Ryan per following comment:
https://github.com/cncf/toc/pull/1024#discussion_r1328547147
> fix: update owners file to remove maintainer

- ADOPTERS.md
Adding https://www.homedepot.com/ to our adopters :)
> chore(adopters): https://www.homedepot.com/

- website/build.sh
- website/layouts/index.html
Followup to https://github.com/cdk8s-team/cdk8s/pull/1428
> fix(website): fails to build
